image: node0.10

script:
  - npm config set registry http://npm.iteam.se:4873/
  - npm install
  - npm test
  - npm version patch

services:
  - redis
  - mongodb

publish:
  npm:
    username: irony
    email: cl@iteam.se
    password: $NPM_PASSWORD
    registry: http://registry.npmjs.org/
